ORG 1000H
CLAVE DB "1234"
MSJ DB "INGRESE LA CLAVE: "
YES DB "ACEPTADO"
NO DB "DENEGADO"
INDEX DB ?

ORG 2000H
MOV BX, OFFSET MSJ
MOV AL, OFFSET YES - OFFSET MSJ
INT 7 
MOV CH, 4
MOV BX, OFFSET INDEX
INGRESO: DEC CH
INT 6 
INC BX
CMP CH, 0
JNZ INGRESO
SUB BX, 4
VERIFICACION: MOV BX, OFFSET CLAVE
ADD BL, CH
MOV AL, [BX]
MOV BX, OFFSET INDEX
ADD BL, CH
MOV AH, [BX]
CMP AL, AH
JNZ DENEGADO
INC CH
CMP CH, 4
JNZ VERIFICACION
MOV BX, OFFSET YES
MOV AL, OFFSET NO - OFFSET YES
INT 7
JMP FINN
DENEGADO: MOV BX, OFFSET NO
MOV AL, OFFSET INDEX - OFFSET NO
INT 7
FINN: HLT
END