ORG 1000H
MSJ DB "INGRESE LA CLAVE (4 CAR)"
CHAR DB ?
CLAVE DB "1234"
YES DB "ACCESO PERMITIDO"
NO DB "ACCESO DENEGADO"
FIN DB ?
INDEX DB ?

ORG 2000H
MOV BX, OFFSET MSJ
MOV AL, OFFSET CHAR - OFFSET MSJ
INT 7
MOV CL,0
MOV BX, OFFSET INDEX
INGRESO: CMP CL, 4 
JZ VERIFICACION
ADD BL, CL
INT 6
INC CL
JMP INGRESO
VERIFICACION: MOV CL, 0
LOOP: CMP CL,4
JZ PERMITIDO
MOV BX, OFFSET CLAVE
ADD BL, CL
MOV AL, [BX]
MOV BX, OFFSET INDEX
ADD BL, CL
MOV AH, [BX]
INC CL
CMP AH,AL
JZ LOOP
MOV BX, OFFSET NO
MOV AL, OFFSET FIN - OFFSET NO
INT 7
JMP FINN
PERMITIDO: MOV BX, OFFSET YES
MOV AL, OFFSET NO - OFFSET YES
INT 7
FINN: INT 0
END